# Generated by Django 2.1.3 on 2018-11-27 23:16

from django.db import migrations
import pandas as pd
import datetime
from django.conf import settings

SANITIZED_DATA_FILE_PATH = settings.DATA_FOLDER / "sanitized_2014_Green_Taxi_Trip_Data.csv"


def create_objects(apps, schema_editor):
    taxi_model = apps.get_model("uber", "Ride")
    objects = []

    df = pd.read_csv(SANITIZED_DATA_FILE_PATH)

    for index, row in df.iterrows():
        pickup_datetime = datetime.datetime.strptime(row["pickup_datetime"], "%m/%d/%Y %I:%M:%S %p")
        dropoff_datetime = datetime.datetime.strptime(row["dropoff_datetime"], "%m/%d/%Y %I:%M:%S %p")

        objects.append(taxi_model(vendorid=int(row["vendorid"]),
                                  pickup_datetime=pickup_datetime,
                                  dropoff_datetime=dropoff_datetime,
                                  rate_code=int(row["rate_code"]),
                                  pickup_longitude=float(row["Pickup_longitude"]),
                                  pickup_latitude=float(row["Pickup_latitude"]),
                                  dropoff_longitude=float(row["Dropoff_longitude"]),
                                  dropoff_latitude=float(row["Dropoff_latitude"]),
                                  passenger_count=int(row["Passenger_count"]),
                                  trip_distance=float(row["Trip_distance"]),
                                  fare_amount=float(row["Fare_amount"]),
                                  tip_amount=float(row["Tip_amount"]),
                                  total_amount=float(row["Total_amount"]),
                                  payment_type=int(row["Payment_type"])
                                  ))

        if len(objects) == 100:
            taxi_model.objects.bulk_create(objects)
            objects = []

    if len(objects):
        taxi_model.objects.bulk_create(objects)


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
